### ISSUE TITLE
New database table for additional elements of the artists.

### ISSUE THREAD

**Issue by Dennisdude** [gittesserakt/StreetbeatzLB#10]
In der offiziellen SMF Webseite sind bei den Künstler die Homepage, Facebook, Instagram, YouTube und Spotify verlinkt, aber nicht alle Künstler haben alle Verlinkungen.

Und es wäre vielleicht auch noch schöner das Genre mit einzutragen und auch irgendwo dann zu zeigen.

**Comment by gittesserakt** [comment]
Additional data, which is required:
- artist images
- social media links (Homepage, Facebook, Instagram, YouTube, Spotify).
- genere
